# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # Pool de conexiones, por defecto es 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  # En desarrollo usamos SQLite
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  # En producción usamos PostgreSQL
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  # En pruebas también podemos usar SQLite, que es rápido
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3